name: Deploy Quote App to Google Cloud

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: devops-464013
  REGION: us-central1
  SERVICE_NAME: quote-app
  REPO_NAME: quotes-repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        
        workload_identity_provider: 'projects/233936726660/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
        service_account: 'quote-deployer@devops-464013.iam.gserviceaccount.com'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:latest

    - name: Deploy to Cloud Run
      id: deploy
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:latest

        flags: '--allow-unauthenticated --port 3000'

    - name: Output Deployed URL
      run: echo "✅ Successfully deployed to ${{ steps.deploy.outputs.url }}"